import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { request } from '../services/api'
import { useStore } from '../hooks/useStore'
export default function AuthPage() {
  const [params] = useSearchParams(); const [mode, setMode] = useState(params.get('mode') === 'signup' ? 'signup' : 'login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const { setUser } = useStore(); const navigate = useNavigate()
  const submit = async event => { event.preventDefault(); setError(''); setLoading(true); try { const data = await request(`/auth/${mode}`, { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('myntraa_token', data.token); localStorage.setItem('myntraa_user', JSON.stringify(data.user)); setUser(data.user); navigate('/account') } catch (err) { setError(err.message) } finally { setLoading(false) } }
  return <section className="auth-page"><div className="auth-card"><div className="auth-brand"><span className="logo-mark">m</span><h1>{mode === 'login' ? 'Welcome back' : 'Join the club'}</h1><p>{mode === 'login' ? 'Your style universe is waiting.' : 'The best of fashion, delivered daily.'}</p></div><form onSubmit={submit}>{mode === 'signup' && <input required placeholder="Your name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/>}<input required type="email" placeholder="Email address" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><input required minLength="6" type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/>{error && <div className="form-error">{error}</div>}<button className="primary-btn full-width" disabled={loading}>{loading ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Create account'}</button></form><p className="auth-switch">{mode === 'login' ? "New to Myntraa?" : 'Already a member?'} <button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Create an account' : 'Log in'}</button></p><Link className="back-link" to="/">← Back to home</Link></div></section>
}
