import { Check, LockKeyhole } from 'lucide-react'
import { Link } from 'react-router-dom'
import EmptyState from '../components/ui/EmptyState'
import { useStore } from '../hooks/useStore'
import { request } from '../services/api'
import { useState } from 'react'
import { money } from '../lib/format'
export default function CheckoutPage() {
  const { cart, updateQty } = useStore(); const [form, setForm] = useState({ customerName: '', phone: '', address: '', city: '', pincode: '' }); const [status, setStatus] = useState(''); const [submitting, setSubmitting] = useState(false)
  if (!cart.length) return <section className="page-section container"><EmptyState title="Nothing to check out" text="Your bag is empty right now." action="Browse products"/></section>
  const total = cart.reduce((sum, item) => sum + item.price * item.qty, 0)
  const submit = async event => { event.preventDefault(); setSubmitting(true); setStatus(''); try { const data = await request('/orders', { method: 'POST', body: JSON.stringify({ ...form, deliveryFee: total >= 799 ? 0 : 99 }) }); setStatus(`Order #${data.orderId} placed successfully.`); cart.forEach(item => updateQty(item.id, 0)) } catch (error) { setStatus(error.message) } finally { setSubmitting(false) } }
  return <section className="page-section container checkout-page"><div className="page-title"><div><span className="eyebrow">ALMOST THERE</span><h1>Checkout</h1></div><span className="secure-label"><LockKeyhole size={14}/> Secure checkout</span></div><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><h2>Delivery details</h2><div className="form-grid"><input required placeholder="Full name" value={form.customerName} onChange={e => setForm({ ...form, customerName: e.target.value })}/><input required type="tel" placeholder="Phone number" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></div><input required placeholder="Address" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })}/><div className="form-grid"><input required placeholder="City" value={form.city} onChange={e => setForm({ ...form, city: e.target.value })}/><input required placeholder="Pincode" value={form.pincode} onChange={e => setForm({ ...form, pincode: e.target.value })}/></div><h2>Payment</h2><div className="payment-placeholder"><Check size={17}/> Online payments and cash on delivery available at launch.</div>{status && <p className="form-error">{status}</p>}<button className="primary-btn full-width" disabled={submitting}>{submitting ? 'Placing order…' : 'Place order'} <Check size={16}/></button></form><aside className="summary"><h2>Order summary</h2>{cart.map(item => <div key={item.id}><span>{item.name} × {item.qty}</span><b>{money(item.price * item.qty)}</b></div>)}<div className="summary-total"><span>Total</span><strong>{money(total + (total >= 799 ? 0 : 99))}</strong></div><small>By placing your order, you agree to our terms.</small></aside></div><Link className="back-link" to="/cart">← Return to bag</Link></section>
}
