import { ArrowRight, Gift, RotateCcw, ShieldCheck, Sparkles } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useStore } from '../hooks/useStore'
import ProductCard from '../components/ui/ProductCard'
import { useEffect, useState } from 'react'
import { getProducts } from '../services/api'
import { ProductGridSkeleton } from '../components/ui/Skeleton'
export default function Home() {
  const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const navigate = useNavigate(); const { wishlist } = useStore()
  useEffect(() => { getProducts().then(data => setProducts(data.products || [])).catch(() => {}).finally(() => setLoading(false)) }, [])
  return <><section className="hero container"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> THE NEW SEASON EDIT</div><h1>Wear your<br/><em>story.</em></h1><p>Curated styles for every version of you. Discover pieces that feel like they were made just for you.</p><Link className="primary-btn" to="/products">Explore collection <ArrowRight size={17}/></Link><div className="hero-stats"><span><strong>12k+</strong> styles</span><span><strong>4.8/5</strong> community rating</span></div></div><div className="hero-art"><div className="sun-orb"/><div className="shape shape-one"/><div className="shape shape-two"/><div className="hero-label">NEW<br/><b>DROP</b></div><div className="model-placeholder">STYLE<br/>IS AN<br/><b>ATTITUDE</b></div><div className="floating-pill pill-top">#feelgoodfashion</div><div className="floating-pill pill-bottom">— SS '25</div></div></section><section className="perks container"><div><Gift className="perk-icon"/><p><b>Curated drops</b><small>Fresh styles every week</small></p></div><div><ShieldCheck className="perk-icon"/><p><b>Quality, always</b><small>Made to be lived in</small></p></div><div><RotateCcw className="perk-icon"/><p><b>Easy returns</b><small>Try it, love it, or return it</small></p></div></section><section className="catalog"><div className="container section-heading"><div><span className="eyebrow">THE EDIT</span><h2>Trending now</h2></div><button className="text-link" onClick={() => navigate('/products')}>View all <ArrowRight size={15}/></button></div>{loading ? <ProductGridSkeleton /> : <div className="container product-grid">{products.slice(0, 4).map(product => <ProductCard key={product.id} product={product}/>)}</div>}</section><section className="newsletter container"><div><span className="eyebrow">IN YOUR INBOX</span><h2>Good things,<br/><em>occasionally.</em></h2></div><div><p>Sign up for thoughtful edits, first access and a little inspiration in your inbox.</p><form className="email-capture" onSubmit={e => e.preventDefault()}><input type="email" placeholder="Your email address" required/><button>Subscribe <ArrowRight size={14}/></button></form></div></section></>
}
